/**
 * Generates supabase/seed.sql from src/data/seed-*.ts.
 * Run: npm run db:seed-sql
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildSeedMenu, buildSeedZones } from "@/data/seed-build";
import { SEED_SETTINGS } from "@/data/seed-settings";

const q = (v: string | null | undefined): string => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const j = (v: unknown): string => (v == null ? "null" : `${q(JSON.stringify(v))}::jsonb`);
const n = (v: number | null | undefined): string => (v == null ? "null" : String(v));
const b = (v: boolean): string => (v ? "true" : "false");
const arr = (v: string[]): string => `array[${v.map(q).join(", ")}]::text[]`;

function insert(table: string, columns: string[], rows: string[][]): string {
  if (rows.length === 0) return "";
  const values = rows.map((r) => `  (${r.join(", ")})`).join(",\n");
  return `insert into public.${table} (${columns.join(", ")}) values\n${values};\n\n`;
}

const menu = buildSeedMenu();
const zones = buildSeedZones();
const s = SEED_SETTINGS;

let sql = `-- GENERATED by scripts/generate-seed-sql.ts — do not edit by hand.
-- Seed menu from the restaurant's Wolt menu + current website.
begin;

`;

sql += insert(
  "categories",
  ["id", "slug", "name", "icon", "sort_order", "is_visible"],
  menu.categories.map((c) => [q(c.id), q(c.slug), j(c.name), q(c.icon), n(c.sortOrder), b(c.isVisible)]),
);

sql += insert(
  "menu_items",
  [
    "id", "slug", "category_id", "name", "description", "image_url", "tags", "is_popular", "is_new",
    "is_hidden", "in_stock", "available_site", "available_wolt", "featured_rank", "sort_order",
    "needs_review", "review_note", "is_combo",
  ],
  menu.items.map((i) => [
    q(i.id), q(i.slug), q(i.categoryId), j(i.name), j(i.description), q(i.imageUrl), arr(i.tags),
    b(i.isPopular), b(i.isNew), b(i.isHidden), b(i.inStock), b(i.availableSite), b(i.availableWolt),
    n(i.featuredRank), n(i.sortOrder), b(i.needsReview), q(i.reviewNote), b(i.isCombo),
  ]),
);

sql += insert(
  "item_variants",
  ["id", "item_id", "label", "price_site", "price_wolt", "sort_order", "is_available"],
  menu.items.flatMap((i) =>
    i.variants.map((v) => [q(v.id), q(i.id), j(v.label), n(v.priceSite), n(v.priceWolt), n(v.sortOrder), b(v.isAvailable)]),
  ),
);

sql += insert(
  "addon_groups",
  ["id", "slug", "name", "min_select", "max_select", "sort_order"],
  menu.addonGroups.map((g) => [q(g.id), q(g.slug), j(g.name), n(g.minSelect), n(g.maxSelect), n(g.sortOrder)]),
);

sql += insert(
  "addon_options",
  ["id", "group_id", "name", "price_site", "price_wolt", "linked_variant_id", "sort_order", "is_available"],
  menu.addonGroups.flatMap((g) =>
    g.options.map((o) => [
      q(o.id), q(g.id), j(o.name), n(o.priceSite), n(o.priceWolt), q(o.linkedVariantId), n(o.sortOrder), b(o.isAvailable),
    ]),
  ),
);

sql += insert(
  "item_addon_groups",
  ["item_id", "group_id", "sort_order"],
  menu.items.flatMap((i) => i.addonGroupIds.map((g, idx) => [q(i.id), q(g), n(idx + 1)])),
);

sql += insert(
  "combos",
  ["id", "item_id", "status"],
  menu.combos.map((c) => [q(c.id), q(c.itemId), q(c.status)]),
);

sql += insert(
  "combo_components",
  ["combo_id", "item_id", "variant_id", "quantity"],
  menu.combos.flatMap((c) => c.components.map((cc) => [q(c.id), q(cc.itemId), q(cc.variantId), n(cc.quantity)])),
);

sql += insert(
  "delivery_zones",
  ["id", "name", "radius_km", "fee", "min_order", "eta_minutes", "sort_order", "is_active"],
  zones.map((z) => [q(z.id), j(z.name), n(z.radiusKm), n(z.fee), n(z.minOrder), n(z.etaMinutes), n(z.sortOrder), b(z.isActive)]),
);

sql += insert(
  "restaurant_settings",
  [
    "id", "name", "phone", "whatsapp", "instagram", "address", "lat", "lng", "google_maps_url",
    "google_review_url", "timezone", "opening_hours", "pickup_enabled", "delivery_enabled",
    "preorder_enabled", "ordering_enabled", "cashback_percent", "wolt_banner_enabled",
    "wolt_banner_text", "hero_image_url", "ai_assistant_enabled", "online_payment_enabled",
  ],
  [[
    "1", q(s.name), q(s.phone), q(s.whatsapp), q(s.instagram), j(s.address), n(s.lat), n(s.lng),
    q(s.googleMapsUrl), q(s.googleReviewUrl), q(s.timezone), j(s.openingHours), b(s.pickupEnabled),
    b(s.deliveryEnabled), b(s.preorderEnabled), b(s.orderingEnabled), n(s.cashbackPercent),
    b(s.woltBannerEnabled), j(s.woltBannerText), q(s.heroImageUrl), b(s.aiAssistantEnabled),
    b(s.onlinePaymentEnabled),
  ]],
);

sql += "insert into public.private_settings (id) values (1);\n\ncommit;\n";

const out = resolve(process.cwd(), "supabase/seed.sql");
writeFileSync(out, sql);
console.log(
  `Wrote ${out}: ${menu.categories.length} categories, ${menu.items.length} items, ` +
    `${menu.items.reduce((a, i) => a + i.variants.length, 0)} variants, ` +
    `${menu.items.filter((i) => i.needsReview).length} flagged for review.`,
);
