/**
 * Generates supabase/seed.sql from the typed seed data in src/data/seed.
 * Run: npm run db:seed:generate
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { seedMenu } from "../src/data/seed/menu";
import { seedPromotions, seedSettings, seedZones } from "../src/data/seed/settings";
import { splitSettings } from "../src/lib/data/settings-keys";

type Value = string | number | boolean | null | object;

function lit(v: Value): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) {
    return `array[${v.map((x) => lit(x)).join(", ")}]::text[]`;
  }
  if (typeof v === "object") return `${lit(JSON.stringify(v))}::jsonb`;
  return `'${v.replace(/'/g, "''")}'`;
}

function insert(table: string, rows: Record<string, Value>[]): string {
  if (rows.length === 0) return "";
  const cols = Object.keys(rows[0]);
  const values = rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(", ")})`).join(",\n");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values};\n`;
}

const { categories, items, optionGroups } = seedMenu;
const out: string[] = [
  "-- Generated by scripts/generate-seed.ts — do not edit by hand.",
  "begin;",
  "truncate public.combo_components, public.item_option_groups, public.options, public.option_groups, public.item_variants, public.items, public.categories, public.delivery_zones, public.promotions, public.settings, public.promo_codes cascade;",
];

out.push(
  insert(
    "categories",
    categories.map((c) => ({ id: c.id, slug: c.slug, name: c.name, role: c.role, art: c.art, sort_order: c.sortOrder, is_visible: c.isVisible })),
  ),
);

out.push(
  insert(
    "items",
    items.map((i) => ({
      id: i.id,
      category_id: i.categoryId,
      slug: i.slug,
      name: i.name,
      description: i.description,
      image_url: i.imageUrl,
      art: i.art,
      variant_label: i.variantLabel,
      available_site: i.availableSite,
      available_wolt: i.availableWolt,
      in_stock: i.inStock,
      is_hidden: i.isHidden,
      is_draft: i.isDraft,
      is_popular: i.isPopular,
      is_new: i.isNew,
      is_spicy: i.isSpicy,
      diet_tags: i.dietTags,
      bestseller_rank: i.bestsellerRank,
      sort_order: i.sortOrder,
      needs_review: i.needsReview,
      review_note: i.reviewNote,
      is_combo: i.isCombo,
    })),
  ),
);

out.push(
  insert(
    "item_variants",
    items.flatMap((i) =>
      i.variants.map((v) => ({
        id: v.id,
        item_id: i.id,
        label: v.label,
        price_site: v.priceSite,
        price_wolt: v.priceWolt,
        available_site: v.availableSite,
        available_wolt: v.availableWolt,
        sort_order: v.sortOrder,
        needs_review: v.needsReview,
        review_note: v.reviewNote,
      })),
    ),
  ),
);

out.push(
  insert(
    "option_groups",
    optionGroups.map((g) => ({ id: g.id, name: g.name, min_select: g.minSelect, max_select: g.maxSelect, sort_order: g.sortOrder, needs_review: g.needsReview })),
  ),
);
out.push(
  insert(
    "options",
    optionGroups.flatMap((g) =>
      g.options.map((o) => ({ id: o.id, group_id: g.id, name: o.name, price_delta: o.priceDelta, is_available: o.isAvailable, sort_order: o.sortOrder })),
    ),
  ),
);
out.push(
  insert(
    "item_option_groups",
    items.flatMap((i) => i.optionGroupIds.map((g, idx) => ({ item_id: i.id, group_id: g, sort_order: idx }))),
  ),
);
out.push(
  insert(
    "combo_components",
    items.flatMap((i) =>
      i.comboComponents.map((c, idx) => ({
        id: c.id,
        combo_item_id: i.id,
        component_item_id: c.itemId,
        component_variant_id: c.variantId,
        quantity: c.quantity,
        label: c.label,
        sort_order: idx,
      })),
    ),
  ),
);

out.push(
  insert(
    "delivery_zones",
    seedZones.map((z) => ({ id: z.id, name: z.name, radius_km: z.radiusKm, fee: z.fee, min_order: z.minOrder, free_from: z.freeFrom, sort_order: z.sortOrder, is_active: z.isActive })),
  ),
);
out.push(
  insert(
    "promotions",
    seedPromotions.map((p) => ({ id: p.id, title: p.title, body: p.body, image_url: p.imageUrl, href: p.href, is_active: p.isActive, sort_order: p.sortOrder })),
  ),
);
out.push(insert("settings", splitSettings(seedSettings).map(({ key, value }) => ({ key, value }))));

// Suggested welcome promo — inactive until the restaurant approves it.
out.push(
  insert("promo_codes", [
    { code: "ALOV10", kind: "percent", value: 10, min_order: 1000, first_order_only: true, is_active: false },
  ]),
);

out.push("commit;");
const file = join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(file, out.filter(Boolean).join("\n"));
console.log(`Wrote ${file}: ${categories.length} categories, ${items.length} items, ${items.reduce((n, i) => n + i.variants.length, 0)} variants.`);
