/**
 * Seed menu, transcribed from the restaurant's current Wolt menu and website.
 *
 * - Prices are in manat here for readability and converted to qəpik on load.
 * - Unless noted, a price is both the Wolt price and the initial site price.
 * - `siteOnly` items exist only on the current website (no Wolt listing).
 * - `review` marks data that looks wrong in the source; it is seeded as-is
 *   with `needs_review = true` so it shows up in the admin validation list.
 *
 * This file is the single source for both `supabase/seed.sql`
 * (generated by `npm run db:seed-sql`) and the in-memory fallback used when
 * Supabase is not configured (local development / demos).
 */
import type { ItemTag, LocalizedText } from "@/lib/types";

export interface SeedVariant {
  label?: LocalizedText;
  site: number;
  /** undefined → same as site; null → not sold on Wolt. */
  wolt?: number | null;
}

export interface SeedItem {
  slug: string;
  name: LocalizedText;
  description?: LocalizedText;
  tags?: ItemTag[];
  popular?: boolean;
  isNew?: boolean;
  featured?: number;
  variants: SeedVariant[];
  siteOnly?: boolean;
  hidden?: boolean;
  review?: string;
  addons?: string[];
}

export interface SeedCategory {
  slug: string;
  name: LocalizedText;
  icon: string;
  items: SeedItem[];
}

export interface SeedAddonOption {
  slug: string;
  name: LocalizedText;
  price: number;
  /** "item-slug#variantIndex" – option is a menu product and follows its price. */
  linked?: string;
  /** Price not confirmed by the restaurant yet — seeded as unavailable until set in admin. */
  unconfirmed?: boolean;
}

export interface SeedAddonGroup {
  slug: string;
  name: LocalizedText;
  min: number;
  max: number;
  options: SeedAddonOption[];
}

export interface SeedComboComponent {
  item: string;
  /** Index into the item's variants; omitted = any variant. */
  variant?: number;
  qty?: number;
}

export interface SeedCombo {
  /** Slug of the orderable combo item (category "kombolar"). */
  item: string;
  status: "active" | "draft";
  components: SeedComboComponent[];
}

const single = (site: number, wolt?: number | null): SeedVariant[] => [{ site, wolt }];

const BREAD = {
  tendir: { az: "Təndir çörəyində", ru: "В тандырном хлебе", en: "In tandoor bread" },
  turk: { az: "Türk çörəyində", ru: "В турецком хлебе", en: "In Turkish bread" },
  lavas: { az: "Lavaşda", ru: "В лаваше", en: "In lavash" },
  limuzin: { az: "Limuzin", ru: "Лимузин", en: "Limuzin (long bun)" },
  tombik: { az: "Tombik", ru: "Томбик", en: "Tombik (round bun)" },
} satisfies Record<string, LocalizedText>;

const SIZE = {
  s: { az: "Kiçik · 25 sm", ru: "Маленькая · 25 см", en: "Small · 25 cm" },
  m: { az: "Orta · 32 sm", ru: "Средняя · 32 см", en: "Medium · 32 cm" },
  l: { az: "Böyük · 35 sm", ru: "Большая · 35 см", en: "Large · 35 cm" },
} satisfies Record<string, LocalizedText>;

const pizza = (s: number, m: number, l: number): SeedVariant[] => [
  { label: SIZE.s, site: s },
  { label: SIZE.m, site: m },
  { label: SIZE.l, site: l },
];

const DONER_ADDONS = ["doner-extras", "sauces", "drinks"];

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    slug: "et-doner",
    name: { az: "Ət dönər (köz)", ru: "Мясной дёнер на углях", en: "Meat döner (charcoal)" },
    icon: "🥙",
    items: [
      {
        slug: "et-doner",
        name: { az: "Ət dönər", ru: "Мясной дёнер", en: "Meat döner" },
        description: {
          az: "Közdə bişmiş ət dönər — çörəyini özün seç.",
          ru: "Мясной дёнер на углях — выберите хлеб.",
          en: "Charcoal-grilled meat döner — pick your bread.",
        },
        tags: ["meat"],
        featured: 1,
        variants: [
          { label: BREAD.tendir, site: 4.1 },
          { label: BREAD.turk, site: 4.1 },
          { label: BREAD.lavas, site: 5.3 },
          { label: BREAD.limuzin, site: 4.6 },
          { label: BREAD.tombik, site: 5.6 },
        ],
        addons: DONER_ADDONS,
      },
      {
        slug: "et-doner-basdirma",
        name: { az: "Ət dönər basdırma", ru: "Мясной дёнер басдырма", en: "Meat döner basdırma" },
        description: {
          az: "Preslənib qızardılmış çörəkdə ət dönər.",
          ru: "Мясной дёнер в прижатом поджаренном хлебе.",
          en: "Meat döner in pressed, toasted bread.",
        },
        tags: ["meat"],
        variants: single(6.1),
        addons: DONER_ADDONS,
      },
      {
        slug: "et-doner-alman",
        name: { az: "Alman dönəri (ət)", ru: "Немецкий дёнер (мясо)", en: "German-style döner (meat)" },
        description: {
          az: "Alman üslubunda ət dönər, təzə tərəvəz və sous ilə.",
          ru: "Мясной дёнер по-немецки со свежими овощами и соусом.",
          en: "German-style meat döner with fresh vegetables and sauce.",
        },
        tags: ["meat"],
        variants: single(6.1),
        addons: DONER_ADDONS,
      },
      {
        slug: "et-doner-hatay",
        name: { az: "Hatay dönər (ət)", ru: "Хатай дёнер (мясо)", en: "Hatay döner (meat)" },
        description: {
          az: "Hatay üslubunda ət dönər.",
          ru: "Мясной дёнер в стиле Хатай.",
          en: "Hatay-style meat döner.",
        },
        tags: ["meat"],
        variants: single(6.9),
        addons: DONER_ADDONS,
      },
      {
        slug: "et-doner-lahmacun",
        name: { az: "Lahmacun arası ət dönər", ru: "Мясной дёнер в лахмаджуне", en: "Meat döner in lahmacun" },
        description: {
          az: "Lahmacuna bükülmüş ət dönər.",
          ru: "Мясной дёнер, завёрнутый в лахмаджун.",
          en: "Meat döner wrapped in lahmacun.",
        },
        tags: ["meat"],
        variants: single(7.6),
        addons: DONER_ADDONS,
      },
    ],
  },
  {
    slug: "toyuq-doner",
    name: { az: "Toyuq dönər (köz)", ru: "Куриный дёнер на углях", en: "Chicken döner (charcoal)" },
    icon: "🥙",
    items: [
      {
        slug: "toyuq-doner",
        name: { az: "Toyuq dönər", ru: "Куриный дёнер", en: "Chicken döner" },
        description: {
          az: "Közdə bişmiş toyuq dönər — çörəyini özün seç.",
          ru: "Куриный дёнер на углях — выберите хлеб.",
          en: "Charcoal-grilled chicken döner — pick your bread.",
        },
        tags: ["chicken"],
        featured: 3,
        variants: [
          { label: BREAD.tendir, site: 3.7 },
          { label: BREAD.turk, site: 3.7 },
          { label: BREAD.lavas, site: 4.6 },
          { label: BREAD.limuzin, site: 3.8 },
          { label: BREAD.tombik, site: 5.3 },
        ],
        addons: DONER_ADDONS,
      },
      {
        slug: "toyuq-doner-basdirma",
        name: { az: "Toyuq dönər basdırma", ru: "Куриный дёнер басдырма", en: "Chicken döner basdırma" },
        description: {
          az: "Preslənib qızardılmış çörəkdə toyuq dönər.",
          ru: "Куриный дёнер в прижатом поджаренном хлебе.",
          en: "Chicken döner in pressed, toasted bread.",
        },
        tags: ["chicken"],
        variants: single(5.3),
        addons: DONER_ADDONS,
      },
      {
        slug: "toyuq-doner-alman",
        name: { az: "Alman dönəri (toyuq)", ru: "Немецкий дёнер (курица)", en: "German-style döner (chicken)" },
        description: {
          az: "Alman üslubunda toyuq dönər, təzə tərəvəz və sous ilə.",
          ru: "Куриный дёнер по-немецки со свежими овощами и соусом.",
          en: "German-style chicken döner with fresh vegetables and sauce.",
        },
        tags: ["chicken"],
        variants: single(4.6),
        review: "4,60 ₼ — digər toyuq dönər növləri ilə müqayisədə ucuz görünür (ət versiyası 6,10 ₼). Qiyməti təsdiqləyin.",
        addons: DONER_ADDONS,
      },
      {
        slug: "toyuq-doner-hatay",
        name: { az: "Hatay dönər (toyuq)", ru: "Хатай дёнер (курица)", en: "Hatay döner (chicken)" },
        description: {
          az: "Hatay üslubunda toyuq dönər.",
          ru: "Куриный дёнер в стиле Хатай.",
          en: "Hatay-style chicken döner.",
        },
        tags: ["chicken"],
        variants: single(6.1),
        addons: DONER_ADDONS,
      },
      {
        slug: "toyuq-doner-lahmacun",
        name: { az: "Lahmacun arası toyuq dönər", ru: "Куриный дёнер в лахмаджуне", en: "Chicken döner in lahmacun" },
        description: {
          az: "Soğan, xiyar, pomidor, göyərti.",
          ru: "Лук, огурец, помидор, зелень.",
          en: "Onion, cucumber, tomato, herbs.",
        },
        tags: ["chicken"],
        variants: single(6.1),
        addons: DONER_ADDONS,
      },
    ],
  },
  {
    slug: "kabablar",
    name: { az: "Kabablar", ru: "Кебабы", en: "Kebabs" },
    icon: "🍢",
    items: [
      {
        slug: "quzu-lulesi",
        name: { az: "Quzu lüləsi", ru: "Люля-кебаб из баранины", en: "Lamb lula kebab" },
        description: { az: "Közdə bişmiş quzu lülə kababı.", ru: "Люля-кебаб из баранины на углях.", en: "Charcoal-grilled minced lamb kebab." },
        tags: ["meat"],
        featured: 2,
        variants: single(10.6),
        addons: ["sauces", "drinks"],
      },
      {
        slug: "quzu-tikesi",
        name: { az: "Quzu tikəsi", ru: "Шашлык из баранины", en: "Lamb shish kebab" },
        description: { az: "Közdə bişmiş quzu tikə kababı.", ru: "Шашлык из баранины на углях.", en: "Charcoal-grilled lamb chunks." },
        tags: ["meat"],
        featured: 4,
        variants: single(12.2),
        addons: ["sauces", "drinks"],
      },
      {
        slug: "quyruq",
        name: { az: "Quyruq", ru: "Курдюк", en: "Lamb tail kebab" },
        description: { az: "Közdə bişmiş quyruq kababı.", ru: "Курдюк на углях.", en: "Charcoal-grilled lamb tail fat." },
        tags: ["meat"],
        variants: single(8.4),
        addons: ["sauces", "drinks"],
      },
      {
        slug: "quzu-ciyeri",
        name: { az: "Quzu ciyəri", ru: "Печень ягнёнка", en: "Lamb liver kebab" },
        description: { az: "Közdə bişmiş quzu ciyəri.", ru: "Печень ягнёнка на углях.", en: "Charcoal-grilled lamb liver." },
        tags: ["meat"],
        popular: true,
        featured: 7,
        variants: single(7.6),
        addons: ["sauces", "drinks"],
      },
      {
        slug: "toyuq-qanadi",
        name: { az: "Toyuq qanadı", ru: "Куриные крылышки", en: "Chicken wings" },
        description: { az: "Közdə bişmiş toyuq qanadları.", ru: "Куриные крылышки на углях.", en: "Charcoal-grilled chicken wings." },
        tags: ["chicken"],
        variants: single(6.9),
        addons: ["sauces", "drinks"],
      },
      {
        slug: "toyuq-filesi",
        name: { az: "Toyuq filesi", ru: "Куриное филе", en: "Chicken fillet kebab" },
        description: { az: "Közdə bişmiş toyuq filesi.", ru: "Куриное филе на углях.", en: "Charcoal-grilled chicken fillet." },
        tags: ["chicken"],
        variants: single(7.6),
        addons: ["sauces", "drinks"],
      },
      {
        slug: "toyuq-lulesi",
        name: { az: "Toyuq lüləsi", ru: "Люля-кебаб из курицы", en: "Chicken lula kebab" },
        description: { az: "Közdə bişmiş toyuq lülə kababı.", ru: "Куриный люля-кебаб на углях.", en: "Charcoal-grilled minced chicken kebab." },
        tags: ["chicken"],
        variants: single(6.9),
        addons: ["sauces", "drinks"],
      },
    ],
  },
  {
    slug: "saurmalar",
    name: { az: "Şaurmalar", ru: "Шаурма", en: "Shawarma" },
    icon: "🌯",
    items: [
      {
        slug: "toyuq-saurma",
        name: { az: "Toyuq şaurma", ru: "Шаурма с курицей", en: "Chicken shawarma" },
        description: { az: "Toyuq şaurma lavaşda.", ru: "Куриная шаурма в лаваше.", en: "Chicken shawarma in lavash." },
        tags: ["chicken"],
        featured: 5,
        variants: [{ label: BREAD.lavas, site: 5.6 }],
        addons: DONER_ADDONS,
      },
      {
        slug: "et-saurma",
        name: { az: "Ət şaurma", ru: "Шаурма с мясом", en: "Meat shawarma" },
        description: { az: "Ət şaurma — çörəkdə və ya lavaşda.", ru: "Мясная шаурма — в хлебе или лаваше.", en: "Meat shawarma — in bread or lavash." },
        tags: ["meat"],
        featured: 6,
        variants: [
          { label: { az: "Çörəkdə", ru: "В хлебе", en: "In bread" }, site: 6.1 },
          { label: BREAD.lavas, site: 6.9 },
        ],
        addons: DONER_ADDONS,
      },
    ],
  },
  {
    slug: "pizzalar",
    name: { az: "Pizzalar", ru: "Пицца", en: "Pizza" },
    icon: "🍕",
    items: [
      {
        slug: "pizza-meksikano",
        name: { az: "Meksikano", ru: "Мексикано", en: "Mexicano" },
        description: {
          az: "Pomidor sousu, mozzarella, mal əti, pepperoni, bibər.",
          ru: "Томатный соус, моцарелла, говядина, пепперони, перец.",
          en: "Tomato sauce, mozzarella, beef, pepperoni, peppers.",
        },
        tags: ["meat", "spicy"],
        variants: pizza(8.7, 12.7, 15.0),
        addons: ["pizza-extras", "drinks"],
      },
      {
        slug: "pizza-sezar",
        name: { az: "Sezar", ru: "Цезарь", en: "Caesar" },
        description: {
          az: "Ağ sous, mozzarella, toyuq, kahı, pomidor, parmesan.",
          ru: "Белый соус, моцарелла, курица, салат, помидор, пармезан.",
          en: "White sauce, mozzarella, chicken, lettuce, tomato, parmesan.",
        },
        tags: ["chicken"],
        variants: pizza(8.7, 11.5, 13.8),
        addons: ["pizza-extras", "drinks"],
      },
      {
        slug: "pizza-marqarita",
        name: { az: "Marqarita", ru: "Маргарита", en: "Margherita" },
        description: {
          az: "Pomidor sousu, mozzarella, reyhan.",
          ru: "Томатный соус, моцарелла, базилик.",
          en: "Tomato sauce, mozzarella, basil.",
        },
        tags: ["vegetarian"],
        variants: pizza(6.9, 9.8, 13.8),
        addons: ["pizza-extras", "drinks"],
      },
      {
        slug: "pizza-vegetarian",
        name: { az: "Vegetarian", ru: "Вегетарианская", en: "Vegetarian" },
        description: {
          az: "Pomidor sousu, mozzarella, göbələk, qarğıdalı, zeytun, bolqar bibəri, pomidor.",
          ru: "Томатный соус, моцарелла, грибы, кукуруза, оливки, болгарский перец, помидор.",
          en: "Tomato sauce, mozzarella, mushrooms, corn, olives, bell pepper, tomato.",
        },
        tags: ["vegetarian"],
        variants: pizza(7.5, 10.4, 12.7),
        addons: ["pizza-extras", "drinks"],
      },
      {
        slug: "pizza-toyuqlu",
        name: { az: "Toyuqlu", ru: "С курицей", en: "Chicken" },
        description: {
          az: "Pomidor sousu, mozzarella, toyuq, göbələk.",
          ru: "Томатный соус, моцарелла, курица, грибы.",
          en: "Tomato sauce, mozzarella, chicken, mushrooms.",
        },
        tags: ["chicken"],
        variants: [{ label: SIZE.s, site: 8.1 }],
        review: "Yalnız bir ölçü var (Kiçik, 8,10 ₼) — Orta və Böyük ölçülərin qiymətini əlavə edin.",
        addons: ["pizza-extras", "drinks"],
      },
      {
        slug: "pizza-sosisli",
        name: { az: "Sosisli", ru: "С сосисками", en: "Sausage" },
        description: {
          az: "Pomidor sousu, mozzarella, sosis, zeytun.",
          ru: "Томатный соус, моцарелла, сосиски, оливки.",
          en: "Tomato sauce, mozzarella, sausage, olives.",
        },
        tags: ["meat"],
        variants: pizza(7.5, 12.7, 13.8),
        addons: ["pizza-extras", "drinks"],
      },
      {
        slug: "pizza-pepperoni",
        name: { az: "Pepperoni", ru: "Пепперони", en: "Pepperoni" },
        description: {
          az: "Pomidor sousu, mozzarella, pepperoni.",
          ru: "Томатный соус, моцарелла, пепперони.",
          en: "Tomato sauce, mozzarella, pepperoni.",
        },
        tags: ["meat"],
        variants: pizza(8.1, 13.3, 13.8),
        addons: ["pizza-extras", "drinks"],
      },
      {
        slug: "pizza-qarisiq",
        name: { az: "Qarışıq", ru: "Ассорти", en: "Mixed" },
        description: {
          az: "Pomidor sousu, mozzarella, salam, sosis, toyuq, göbələk, zeytun, bolqar bibəri.",
          ru: "Томатный соус, моцарелла, салями, сосиски, курица, грибы, оливки, болгарский перец.",
          en: "Tomato sauce, mozzarella, salami, sausage, chicken, mushrooms, olives, bell pepper.",
        },
        tags: ["meat", "chicken"],
        variants: pizza(8.7, 13.3, 16.1),
        addons: ["pizza-extras", "drinks"],
      },
    ],
  },
  {
    slug: "burgerler",
    name: { az: "Burgerlər", ru: "Бургеры", en: "Burgers" },
    icon: "🍔",
    items: [
      {
        slug: "double-toyuq-burger",
        name: { az: "Double toyuq burger", ru: "Дабл бургер с курицей", en: "Double chicken burger" },
        description: { az: "İki toyuq kotleti ilə burger.", ru: "Бургер с двумя куриными котлетами.", en: "Burger with two chicken patties." },
        tags: ["chicken"],
        variants: single(9.9),
        addons: ["sauces", "drinks"],
      },
      {
        slug: "double-et-burger",
        name: { az: "Double ət burger", ru: "Дабл бургер с говядиной", en: "Double beef burger" },
        description: { az: "İki ət kotleti ilə burger.", ru: "Бургер с двумя говяжьими котлетами.", en: "Burger with two beef patties." },
        tags: ["meat"],
        variants: single(10.6),
        addons: ["sauces", "drinks"],
      },
      {
        slug: "double-toyuq-cizburger",
        name: { az: "Double toyuq çizburger", ru: "Дабл чизбургер с курицей", en: "Double chicken cheeseburger" },
        description: {
          az: "İki toyuq kotleti və pendir ilə.",
          ru: "Две куриные котлеты и сыр.",
          en: "Two chicken patties with cheese.",
        },
        tags: ["chicken"],
        variants: single(10.6),
        addons: ["sauces", "drinks"],
      },
      {
        slug: "double-et-cizburger",
        name: { az: "Double ət çizburger", ru: "Дабл чизбургер с говядиной", en: "Double beef cheeseburger" },
        description: {
          az: "İki ət kotleti və pendir ilə.",
          ru: "Две говяжьи котлеты и сыр.",
          en: "Two beef patties with cheese.",
        },
        tags: ["meat"],
        variants: single(10.6),
        addons: ["sauces", "drinks"],
      },
    ],
  },
  {
    slug: "kombolar",
    name: { az: "Kombolar", ru: "Комбо", en: "Combos" },
    icon: "🎁",
    items: [
      {
        slug: "kombo-toyuq-cizburger-fri",
        name: { az: "Toyuq çizburger + kartof fri", ru: "Чизбургер с курицей + картофель фри", en: "Chicken cheeseburger + fries" },
        description: { az: "Double toyuq çizburger və kartof fri.", ru: "Дабл чизбургер с курицей и картофель фри.", en: "Double chicken cheeseburger and fries." },
        tags: ["chicken"],
        variants: single(9.9),
      },
      {
        slug: "kombo-et-cizburger-fri",
        name: { az: "Ət çizburger + kartof fri", ru: "Чизбургер с говядиной + картофель фри", en: "Beef cheeseburger + fries" },
        description: { az: "Double ət çizburger və kartof fri.", ru: "Дабл чизбургер с говядиной и картофель фри.", en: "Double beef cheeseburger and fries." },
        tags: ["meat"],
        variants: single(11.4),
      },
      {
        slug: "kombo-toyuq-burger-fri-kola",
        name: {
          az: "Toyuq burger + kartof fri + Coca-Cola 300 ml",
          ru: "Бургер с курицей + картофель фри + Coca-Cola 300 мл",
          en: "Chicken burger + fries + Coca-Cola 300 ml",
        },
        description: {
          az: "Double toyuq burger, kartof fri və Coca-Cola 300 ml.",
          ru: "Дабл бургер с курицей, картофель фри и Coca-Cola 300 мл.",
          en: "Double chicken burger, fries and Coca-Cola 300 ml.",
        },
        tags: ["chicken"],
        variants: single(10.6),
      },
      {
        slug: "kombo-naggets-fri",
        name: { az: "Toyuq naggets + kartof fri", ru: "Куриные наггетсы + картофель фри", en: "Chicken nuggets + fries" },
        description: { az: "Toyuq naggets və kartof fri.", ru: "Куриные наггетсы и картофель фри.", en: "Chicken nuggets and fries." },
        tags: ["chicken"],
        variants: single(8.4),
      },
      {
        slug: "kombo-baby-pizza",
        name: { az: "Baby pizza + kartof fri + meyvə şirəsi", ru: "Беби-пицца + картофель фри + сок", en: "Baby pizza + fries + juice" },
        description: {
          az: "Kiçik pizza, kartof fri və meyvə şirəsi.",
          ru: "Маленькая пицца, картофель фри и сок.",
          en: "Small pizza, fries and fruit juice.",
        },
        variants: single(10.6),
        review: "\"Baby pizza\" menyuda ayrıca məhsul kimi yoxdur — hansı pizza olduğunu və ölçüsünü dəqiqləşdirin.",
      },
      // Draft combo ideas (hidden until an admin activates them).
      {
        slug: "kombo-doner-ayran",
        name: { az: "Dönər + Ayran", ru: "Дёнер + Айран", en: "Döner + Ayran" },
        description: {
          az: "Təndir çörəyində ət dönər və Azərsüd Ayran 200 ml.",
          ru: "Мясной дёнер в тандырном хлебе и айран Azərsüd 200 мл.",
          en: "Meat döner in tandoor bread and Azərsüd Ayran 200 ml.",
        },
        tags: ["meat"],
        variants: single(4.9, null),
        siteOnly: true,
        hidden: true,
      },
      {
        slug: "kombo-aile-paketi",
        name: { az: "Ailə paketi", ru: "Семейный набор", en: "Family pack" },
        description: {
          az: "Böyük Qarışıq pizza + 4 lahmacun + Coca-Cola 1 L.",
          ru: "Большая пицца Ассорти + 4 лахмаджуна + Coca-Cola 1 л.",
          en: "Large Mixed pizza + 4 lahmacun + Coca-Cola 1 L.",
        },
        tags: ["meat"],
        variants: single(31.9, null),
        siteOnly: true,
        hidden: true,
      },
      {
        slug: "kombo-kabab-duo",
        name: { az: "Kabab duo", ru: "Кебаб дуо", en: "Kebab duo" },
        description: {
          az: "Quzu lüləsi + toyuq lüləsi + 2 Ayran.",
          ru: "Люля из баранины + люля из курицы + 2 айрана.",
          en: "Lamb lula + chicken lula + 2 ayran.",
        },
        tags: ["meat", "chicken"],
        variants: single(17.9, null),
        siteOnly: true,
        hidden: true,
      },
    ],
  },
  {
    slug: "lahmacunlar",
    name: { az: "Lahmacunlar", ru: "Лахмаджун", en: "Lahmacun" },
    icon: "🫓",
    items: [
      {
        slug: "lahmacun-sade",
        name: { az: "Sadə lahmacun", ru: "Лахмаджун классический", en: "Classic lahmacun" },
        description: { az: "Nazik xəmir üzərində ədviyyatlı qiymə.", ru: "Тонкое тесто с пряным фаршем.", en: "Thin dough topped with spiced minced meat." },
        tags: ["meat"],
        variants: single(3.8),
        addons: ["drinks"],
      },
      {
        slug: "lahmacun-acili",
        name: { az: "Acılı lahmacun", ru: "Острый лахмаджун", en: "Spicy lahmacun" },
        description: { az: "Acı bibərli lahmacun.", ru: "Лахмаджун с острым перцем.", en: "Lahmacun with hot pepper." },
        tags: ["meat", "spicy"],
        variants: single(3.8),
        addons: ["drinks"],
      },
      {
        slug: "lahmacun-pendirli",
        name: { az: "Pendirli lahmacun", ru: "Лахмаджун с сыром", en: "Cheese lahmacun" },
        description: { az: "Pendirli lahmacun.", ru: "Лахмаджун с сыром.", en: "Lahmacun with cheese." },
        tags: ["meat"],
        variants: single(4.6),
        addons: ["drinks"],
      },
      {
        slug: "lahmacun-qozlu",
        name: { az: "Qozlu lahmacun", ru: "Лахмаджун с орехами", en: "Walnut lahmacun" },
        description: { az: "Qozlu lahmacun.", ru: "Лахмаджун с грецкими орехами.", en: "Lahmacun with walnuts." },
        tags: ["meat"],
        variants: single(4.6),
        addons: ["drinks"],
      },
    ],
  },
  {
    slug: "pideler",
    name: { az: "Pidələr", ru: "Пиде", en: "Pide" },
    icon: "🥖",
    items: [
      { slug: "pide-qiymeli", name: { az: "Qiyməli pide", ru: "Пиде с фаршем", en: "Minced meat pide" }, tags: ["meat"], variants: single(10.6), review: "Təsvir (tərkib) yoxdur — əlavə edin.", addons: ["drinks"] },
      { slug: "pide-pendirli", name: { az: "Pendirli pide", ru: "Пиде с сыром", en: "Cheese pide" }, tags: ["vegetarian"], variants: single(9.1), review: "Təsvir (tərkib) yoxdur — əlavə edin.", addons: ["drinks"] },
      { slug: "pide-sucuqlu", name: { az: "Sucuqlu pide", ru: "Пиде с суджуком", en: "Sucuk pide" }, tags: ["meat"], variants: single(10.6), review: "Təsvir (tərkib) yoxdur — əlavə edin.", addons: ["drinks"] },
      { slug: "pide-toyuqlu", name: { az: "Toyuqlu pide", ru: "Пиде с курицей", en: "Chicken pide" }, tags: ["chicken"], variants: single(10.6), review: "Təsvir (tərkib) yoxdur — əlavə edin.", addons: ["drinks"] },
      { slug: "pide-sosisli", name: { az: "Sosisli pide", ru: "Пиде с сосисками", en: "Sausage pide" }, tags: ["meat"], variants: single(10.6), review: "Təsvir (tərkib) yoxdur — əlavə edin.", addons: ["drinks"] },
    ],
  },
  {
    slug: "hot-rolls",
    name: { az: "Hot Rolls", ru: "Хот-роллы", en: "Hot rolls" },
    icon: "🍣",
    items: [
      {
        slug: "isti-chicken-roll",
        name: { az: "İsti Chicken Roll", ru: "Горячий ролл с курицей", en: "Hot Chicken Roll" },
        description: { az: "Toyuqlu isti roll.", ru: "Горячий ролл с курицей.", en: "Hot roll with chicken." },
        tags: ["chicken"],
        variants: single(9.1),
      },
      {
        slug: "isti-ebi-roll",
        name: { az: "İsti Ebi Roll", ru: "Горячий ролл Эби", en: "Hot Ebi Roll" },
        description: { az: "Krevetli isti roll.", ru: "Горячий ролл с креветкой.", en: "Hot roll with shrimp." },
        tags: ["seafood"],
        variants: single(12.2),
      },
      {
        slug: "isti-california-roll",
        name: { az: "İsti California Roll", ru: "Горячий ролл Калифорния", en: "Hot California Roll" },
        description: { az: "İsti California roll.", ru: "Горячий ролл Калифорния.", en: "Hot California roll." },
        tags: ["seafood"],
        variants: single(12.2),
      },
    ],
  },
  {
    slug: "qelyanaltilar",
    name: { az: "Qəlyanaltılar", ru: "Закуски", en: "Snacks" },
    icon: "🍟",
    items: [
      {
        slug: "kartof-fri",
        name: { az: "Kartof fri", ru: "Картофель фри", en: "French fries" },
        description: { az: "Qızardılmış kartof.", ru: "Картофель фри.", en: "Crispy fried potatoes." },
        tags: ["vegetarian"],
        // Site price confirmed by the restaurant (2,50 ₼); the Wolt listing shows 12,10 ₼.
        variants: single(2.5, 12.1),
        review: "Wolt siyahısında 12,10 ₼ göstərilir (sayt qiyməti 2,50 ₼) — Wolt qiymətini düzəldin.",
        addons: ["sauces"],
      },
      {
        slug: "toyuq-naggets",
        name: { az: "Toyuq naggets", ru: "Куриные наггетсы", en: "Chicken nuggets" },
        description: { az: "Xırtıldayan toyuq naggets.", ru: "Хрустящие куриные наггетсы.", en: "Crispy chicken nuggets." },
        tags: ["chicken"],
        variants: [
          { label: { az: "3 əd.", ru: "3 шт.", en: "3 pcs" }, site: 3.8 },
          { label: { az: "6 əd.", ru: "6 шт.", en: "6 pcs" }, site: 4.6 },
        ],
        review: "6 əd. (4,60 ₼) 3 əd. (3,80 ₼) ilə müqayisədə şübhəli dərəcədə ucuzdur. Qiymətləri təsdiqləyin.",
        addons: ["sauces"],
      },
      {
        slug: "ciy-kufte",
        name: { az: "Çiy küftə", ru: "Чиг кёфте", en: "Çiğ köfte" },
        description: { az: "Ədviyyatlı bulqur küftəsi.", ru: "Пряные котлетки из булгура.", en: "Spicy bulgur köfte." },
        tags: ["spicy"],
        variants: single(7.6),
      },
      {
        slug: "ciy-kufte-durum",
        name: { az: "Çiy küftə dürüm", ru: "Чиг кёфте дюрюм", en: "Çiğ köfte wrap" },
        description: { az: "Lavaşa bükülmüş çiy küftə.", ru: "Чиг кёфте в лаваше.", en: "Çiğ köfte wrapped in lavash." },
        tags: ["spicy"],
        variants: single(7.6),
      },
      {
        slug: "pendir-cubuqlari",
        name: { az: "Pendir çubuqları", ru: "Сырные палочки", en: "Cheese sticks" },
        description: { az: "Qızardılmış pendir çubuqları.", ru: "Жареные сырные палочки.", en: "Fried cheese sticks." },
        tags: ["vegetarian"],
        variants: [
          { label: { az: "4 əd.", ru: "4 шт.", en: "4 pcs" }, site: 4.6 },
          { site: 7.6 },
        ],
        review: "Wolt-da eyni məhsul iki dəfə var (4 əd. 4,60 ₼ və 7,60 ₼). İkinci variantın adı yoxdur — ölçüsünü yazın və ya silin.",
        addons: ["sauces"],
      },
    ],
  },
  {
    slug: "sorbalar",
    name: { az: "Şorbalar", ru: "Супы", en: "Soups" },
    icon: "🍲",
    items: [
      {
        slug: "merci-sorbasi",
        name: { az: "Mərci şorbası", ru: "Чечевичный суп", en: "Lentil soup" },
        description: { az: "Ənənəvi mərci şorbası.", ru: "Традиционный чечевичный суп.", en: "Traditional lentil soup." },
        popular: true,
        variants: single(3.8),
      },
      {
        slug: "toyuq-sorbasi",
        name: { az: "Toyuq şorbası", ru: "Куриный суп", en: "Chicken soup" },
        description: { az: "Təzə toyuq əti ilə.", ru: "Со свежим куриным мясом.", en: "With fresh chicken." },
        tags: ["chicken"],
        variants: single(3.0, 4.6),
      },
      {
        slug: "dovga",
        name: { az: "Dovğa", ru: "Довга", en: "Dovga" },
        description: {
          az: "Qatıq və yaşıllıqla hazırlanan milli şorba.",
          ru: "Национальный суп из катыка и зелени.",
          en: "National yogurt and herb soup.",
        },
        tags: ["vegetarian"],
        variants: single(3.0, null),
        siteOnly: true,
      },
    ],
  },
  {
    slug: "salatlar",
    name: { az: "Salatlar", ru: "Салаты", en: "Salads" },
    icon: "🥗",
    items: [
      {
        slug: "coban-salati",
        name: { az: "Çoban salatı", ru: "Салат Чобан", en: "Shepherd's salad" },
        description: { az: "Təzə pomidor və xiyar.", ru: "Свежие помидоры и огурцы.", en: "Fresh tomato and cucumber." },
        tags: ["vegetarian"],
        variants: single(3.0, 4.6),
      },
      {
        slug: "sezar-salati",
        name: { az: "Sezar salatı", ru: "Салат Цезарь", en: "Caesar salad" },
        description: { az: "Klassik Sezar, təzə yaşıllıqlarla.", ru: "Классический Цезарь со свежей зеленью.", en: "Classic Caesar with fresh greens." },
        variants: single(7.0, null),
        siteOnly: true,
      },
      {
        slug: "mimoza-salati",
        name: { az: "Mimoza salatı", ru: "Салат Мимоза", en: "Mimosa salad" },
        description: { az: "Qatlı, çuğundur ilə.", ru: "Слоёный, со свёклой.", en: "Layered, with beetroot." },
        variants: single(4.5, null),
        siteOnly: true,
      },
      {
        slug: "toyuq-salati",
        name: { az: "Toyuq salatı", ru: "Салат с курицей", en: "Chicken salad" },
        description: { az: "Qızardılmış toyuq əti ilə.", ru: "С жареной курицей.", en: "With fried chicken." },
        tags: ["chicken"],
        variants: single(4.0, null),
        siteOnly: true,
      },
      {
        slug: "paytaxt-salati",
        name: { az: "Paytaxt salatı", ru: "Салат Столичный", en: "Capital salad" },
        description: { az: "Ənənəvi Paytaxt salatı.", ru: "Традиционный салат Столичный.", en: "Traditional Olivier-style salad." },
        variants: single(3.5, null),
        siteOnly: true,
      },
    ],
  },
  {
    slug: "ickiler",
    name: { az: "İçkilər", ru: "Напитки", en: "Drinks" },
    icon: "🥤",
    items: [
      {
        slug: "coca-cola",
        name: { az: "Coca-Cola", ru: "Coca-Cola", en: "Coca-Cola" },
        description: { az: "Soyuq Coca-Cola.", ru: "Холодная Coca-Cola.", en: "Chilled Coca-Cola." },
        variants: [
          { label: { az: "300 ml", ru: "300 мл", en: "300 ml" }, site: 1.6 },
          { label: { az: "500 ml", ru: "500 мл", en: "500 ml" }, site: 2.6 },
          { label: { az: "1 L", ru: "1 л", en: "1 L" }, site: 4.6 },
          { label: { az: "330 ml", ru: "330 мл", en: "330 ml" }, site: 4.6 },
        ],
        review: "330 ml (4,60 ₼) 500 ml-dən (2,60 ₼) bahadır — qiyməti təsdiqləyin.",
      },
      {
        slug: "fanta",
        name: { az: "Fanta", ru: "Fanta", en: "Fanta" },
        description: { az: "Soyuq Fanta.", ru: "Холодная Fanta.", en: "Chilled Fanta." },
        variants: [
          { label: { az: "300 ml", ru: "300 мл", en: "300 ml" }, site: 1.6 },
          { label: { az: "500 ml", ru: "500 мл", en: "500 ml" }, site: 2.6 },
          { label: { az: "1 L", ru: "1 л", en: "1 L" }, site: 4.6 },
          { label: { az: "330 ml", ru: "330 мл", en: "330 ml" }, site: 4.6 },
        ],
        review: "330 ml (4,60 ₼) 500 ml-dən (2,60 ₼) bahadır — qiyməti təsdiqləyin.",
      },
      {
        slug: "sprite",
        name: { az: "Sprite", ru: "Sprite", en: "Sprite" },
        description: { az: "Soyuq Sprite.", ru: "Холодный Sprite.", en: "Chilled Sprite." },
        variants: [
          { label: { az: "300 ml", ru: "300 мл", en: "300 ml" }, site: 1.6 },
          { label: { az: "500 ml", ru: "500 мл", en: "500 ml" }, site: 2.6 },
        ],
      },
      {
        slug: "ayran",
        name: { az: "Azərsüd Ayran 200 ml", ru: "Айран Azərsüd 200 мл", en: "Azərsüd Ayran 200 ml" },
        description: { az: "Sərin ayran.", ru: "Прохладный айран.", en: "Chilled ayran." },
        tags: ["vegetarian"],
        popular: true,
        featured: 8,
        variants: single(1.1),
      },
      {
        slug: "cappy-multimeyve",
        name: { az: "Cappy multimeyvə 200 ml", ru: "Cappy мультифрукт 200 мл", en: "Cappy multifruit 200 ml" },
        description: { az: "Meyvə şirəsi.", ru: "Фруктовый сок.", en: "Fruit juice." },
        variants: single(2.3),
      },
      {
        slug: "fuse-tea-manqo",
        name: { az: "Fuse Tea Manqo-Ananas 500 ml", ru: "Fuse Tea манго-ананас 500 мл", en: "Fuse Tea Mango-Pineapple 500 ml" },
        description: { az: "Soyuq çay.", ru: "Холодный чай.", en: "Iced tea." },
        variants: single(3.0),
      },
      {
        slug: "fuse-tea-saftali",
        name: { az: "Fuse Tea Şaftalı 500 ml", ru: "Fuse Tea персик 500 мл", en: "Fuse Tea Peach 500 ml" },
        description: { az: "Soyuq çay.", ru: "Холодный чай.", en: "Iced tea." },
        variants: single(3.0),
      },
    ],
  },
];

/**
 * Extras and sauce prices are placeholders (the restaurant has not confirmed them),
 * so those options are seeded as unavailable and stay hidden until an admin sets
 * the real price. Drink add-ons follow the drink's own menu price.
 */
export const SEED_ADDON_GROUPS: SeedAddonGroup[] = [
  {
    slug: "doner-extras",
    name: { az: "Əlavələr", ru: "Добавки", en: "Extras" },
    min: 0,
    max: 3,
    options: [
      { slug: "extra-cheese", name: { az: "Əlavə pendir", ru: "Доп. сыр", en: "Extra cheese" }, price: 1.0, unconfirmed: true },
      { slug: "extra-meat", name: { az: "Əlavə ət", ru: "Доп. мясо", en: "Extra meat" }, price: 2.5, unconfirmed: true },
      { slug: "jalapeno", name: { az: "Halapenyo", ru: "Халапеньо", en: "Jalapeño" }, price: 0.7, unconfirmed: true },
    ],
  },
  {
    slug: "pizza-extras",
    name: { az: "Pizza əlavələri", ru: "Добавки к пицце", en: "Pizza extras" },
    min: 0,
    max: 4,
    options: [
      { slug: "extra-mozzarella", name: { az: "Əlavə mozzarella", ru: "Доп. моцарелла", en: "Extra mozzarella" }, price: 1.5, unconfirmed: true },
      { slug: "mushrooms", name: { az: "Göbələk", ru: "Грибы", en: "Mushrooms" }, price: 1.0, unconfirmed: true },
      { slug: "olives", name: { az: "Zeytun", ru: "Оливки", en: "Olives" }, price: 0.8, unconfirmed: true },
      { slug: "pizza-jalapeno", name: { az: "Halapenyo", ru: "Халапеньо", en: "Jalapeño" }, price: 0.7, unconfirmed: true },
    ],
  },
  {
    slug: "sauces",
    name: { az: "Souslar", ru: "Соусы", en: "Sauces" },
    min: 0,
    max: 3,
    options: [
      { slug: "ketchup", name: { az: "Ketçup", ru: "Кетчуп", en: "Ketchup" }, price: 0.5, unconfirmed: true },
      { slug: "mayo", name: { az: "Mayonez", ru: "Майонез", en: "Mayonnaise" }, price: 0.5, unconfirmed: true },
      { slug: "garlic-sauce", name: { az: "Sarımsaqlı sous", ru: "Чесночный соус", en: "Garlic sauce" }, price: 0.7, unconfirmed: true },
      { slug: "hot-sauce", name: { az: "Acı sous", ru: "Острый соус", en: "Hot sauce" }, price: 0.5, unconfirmed: true },
    ],
  },
  {
    slug: "drinks",
    name: { az: "İçki əlavə et", ru: "Добавить напиток", en: "Add a drink" },
    min: 0,
    max: 2,
    options: [
      { slug: "drink-ayran", name: { az: "Ayran 200 ml", ru: "Айран 200 мл", en: "Ayran 200 ml" }, price: 1.1, linked: "ayran#0" },
      { slug: "drink-cola", name: { az: "Coca-Cola 300 ml", ru: "Coca-Cola 300 мл", en: "Coca-Cola 300 ml" }, price: 1.6, linked: "coca-cola#0" },
      { slug: "drink-fanta", name: { az: "Fanta 300 ml", ru: "Fanta 300 мл", en: "Fanta 300 ml" }, price: 1.6, linked: "fanta#0" },
      { slug: "drink-sprite", name: { az: "Sprite 300 ml", ru: "Sprite 300 мл", en: "Sprite 300 ml" }, price: 1.6, linked: "sprite#0" },
    ],
  },
];

export const SEED_COMBOS: SeedCombo[] = [
  { item: "kombo-toyuq-cizburger-fri", status: "active", components: [{ item: "double-toyuq-cizburger" }, { item: "kartof-fri" }] },
  { item: "kombo-et-cizburger-fri", status: "active", components: [{ item: "double-et-cizburger" }, { item: "kartof-fri" }] },
  {
    item: "kombo-toyuq-burger-fri-kola",
    status: "active",
    components: [{ item: "double-toyuq-burger" }, { item: "kartof-fri" }, { item: "coca-cola", variant: 0 }],
  },
  { item: "kombo-naggets-fri", status: "active", components: [{ item: "toyuq-naggets" }, { item: "kartof-fri" }] },
  // "Baby pizza" is not a menu product, so this combo cannot be auto-detected in the cart.
  { item: "kombo-baby-pizza", status: "active", components: [] },
  // Draft ideas — review prices, then activate in the admin panel.
  { item: "kombo-doner-ayran", status: "draft", components: [{ item: "et-doner", variant: 0 }, { item: "ayran" }] },
  {
    item: "kombo-aile-paketi",
    status: "draft",
    components: [
      { item: "pizza-qarisiq", variant: 2 },
      { item: "lahmacun-sade", qty: 4 },
      { item: "coca-cola", variant: 2 },
    ],
  },
  {
    item: "kombo-kabab-duo",
    status: "draft",
    components: [{ item: "quzu-lulesi" }, { item: "toyuq-lulesi" }, { item: "ayran", qty: 2 }],
  },
];
